[package]
name = "ju-tcs-rust-23-04"
version = "0.2.1"
edition = "2021"
license = "MIT"
description = "package created for rust labs at Jagiellonian University"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
